# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.4.2" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.4.2.tgz";
        sha512 = "7Bl2rALb7HpvXFL7TETNzKSAeBVCPHELzc0C//9FCxN8nsiueWSJBqaF+2oIJScyILStASR/Cx5WMkXGYTiJFA==";
      };
    };
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 = "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "acorn-6.1.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "6.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-6.1.1.tgz";
        sha512 = "jPTiwtOxaHNaAPg/dmrJ/beuzLRnXtB0kQPQ8JpotKJgTB6rX6c8mlf315941pyjBSaPg8NHXS9fhP4u17DpGA==";
      };
    };
    "acorn-dynamic-import-4.0.0" = {
      name = "acorn-dynamic-import";
      packageName = "acorn-dynamic-import";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-dynamic-import/-/acorn-dynamic-import-4.0.0.tgz";
        sha512 = "d3OEjQV4ROpoflsnUA8HozoIR504TFxNivYEUi6uwz0IYhBkTDXGuWlNdMtybRt3nqVx/L6XqMt0FxkXuWKZhw==";
      };
    };
    "acorn-node-1.6.2" = {
      name = "acorn-node";
      packageName = "acorn-node";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-node/-/acorn-node-1.6.2.tgz";
        sha512 = "rIhNEZuNI8ibQcL7ANm/mGyPukIaZsRNX9psFNQURyJW0nu6k8wjSDld20z6v2mDBWqX13pIEnk9gGZJHIlEXg==";
      };
    };
    "acorn-walk-6.1.1" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "6.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-6.1.1.tgz";
        sha512 = "OtUw6JUTgxA2QoqqmrmQ7F2NYqiBPi/L2jqHyFtllhOUvXYQXf0Z1CYUinIfyT4bTCGmrA7gX9FvHA81uzCoVw==";
      };
    };
    "ajv-4.11.8" = {
      name = "ajv";
      packageName = "ajv";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-4.11.8.tgz";
        sha1 = "82ffb02b29e662ae53bdc20af15947706739c536";
      };
    };
    "ajv-6.10.0" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.10.0.tgz";
        sha512 = "nffhOpkymDECQyR0mnsUtoCE8RlX38G0rYP+wgLWFyZuUyuuojSSvi/+euOiQBIn63whYwYVIIH1TvE3tu4OEg==";
      };
    };
    "array-filter-0.0.1" = {
      name = "array-filter";
      packageName = "array-filter";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-filter/-/array-filter-0.0.1.tgz";
        sha1 = "7da8cf2e26628ed732803581fd21f67cacd2eeec";
      };
    };
    "array-map-0.0.0" = {
      name = "array-map";
      packageName = "array-map";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-map/-/array-map-0.0.0.tgz";
        sha1 = "88a2bab73d1cf7bcd5c1b118a003f66f665fa662";
      };
    };
    "array-reduce-0.0.0" = {
      name = "array-reduce";
      packageName = "array-reduce";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-reduce/-/array-reduce-0.0.0.tgz";
        sha1 = "173899d3ffd1c7d9383e4479525dbe278cab5f2b";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "asn1.js-4.10.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.10.1.tgz";
        sha512 = "p32cOF5q0Zqs9uBiONKYLm6BClCoBCM5O9JfeUSlnQLBTxYdTK+pW+nXflm8UkKd2UYlEbYz5qEi0JuZR9ckSw==";
      };
    };
    "asn1.js-5.0.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-5.0.1.tgz";
        sha512 = "aO8EaEgbgqq77IEw+1jfx5c9zTbzvkfuRBuZsSsPnTHMkmd5AI4J6OtITLZFa381jReeaQL67J0GBTUu0+ZTVw==";
      };
    };
    "assert-1.4.1" = {
      name = "assert";
      packageName = "assert";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.4.1.tgz";
        sha1 = "99912d591836b5a6f5b345c0f07eefc08fc65d91";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.8.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.8.0.tgz";
        sha512 = "ReZxvNHIOv88FlT7rxcXIIC0fPt4KZqZbOlivyWtXLt8ESx84zd3kMC6iK5jVeS2qt+g7ftS7ye4fi06X5rtRQ==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base-x-3.0.5" = {
      name = "base-x";
      packageName = "base-x";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-3.0.5.tgz";
        sha512 = "C3picSgzPSLE+jW3tcBzJoGwitOtazb5B+5YmAxZm2ybmTi9LNgAtDO/jjVEBZwHoXmDBZ9m/IELj3elJVRBcA==";
      };
    };
    "base64-js-1.3.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz";
        sha512 = "ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw==";
      };
    };
    "base64url-3.0.1" = {
      name = "base64url";
      packageName = "base64url";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64url/-/base64url-3.0.1.tgz";
        sha512 = "ir1UPr3dkwexU7FdV8qBBbNDRUhMmIekYMFZfi+C/sLNnRESKPl23nB9b2pltqfOQNnGzsDdId90AEtG5tCx4A==";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "bech32-1.1.3" = {
      name = "bech32";
      packageName = "bech32";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bech32/-/bech32-1.1.3.tgz";
        sha512 = "yuVFUvrNcoJi0sv5phmqc6P+Fl1HjRDRNOOkHY2X/3LBy2bIGNSFx4fZ95HMaXHupuS7cZR15AsvtmCIF4UEyg==";
      };
    };
    "bigi-1.4.2" = {
      name = "bigi";
      packageName = "bigi";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bigi/-/bigi-1.4.2.tgz";
        sha1 = "9c665a95f88b8b08fc05cfd731f561859d725825";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "bip32-1.0.2" = {
      name = "bip32";
      packageName = "bip32";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip32/-/bip32-1.0.2.tgz";
        sha512 = "kedLYj8yvYzND+EfzeoMSlGiN7ImiRBF/MClJSZPkMfcU+OQO7ZpL5L/Yg+TunebBZIHhunstiQF//KLKSF5rg==";
      };
    };
    "bip39-2.5.0" = {
      name = "bip39";
      packageName = "bip39";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip39/-/bip39-2.5.0.tgz";
        sha512 = "xwIx/8JKoT2+IPJpFEfXoWdYwP7UVAoUxxLNfGCfVowaJE7yg1Y5B1BVPqlUNsBq5/nGwmFkwRJ8xDW4sX8OdA==";
      };
    };
    "bip66-1.1.5" = {
      name = "bip66";
      packageName = "bip66";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip66/-/bip66-1.1.5.tgz";
        sha1 = "01fa8748785ca70955d5011217d1b3139969ca22";
      };
    };
    "bitcoin-ops-1.4.1" = {
      name = "bitcoin-ops";
      packageName = "bitcoin-ops";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bitcoin-ops/-/bitcoin-ops-1.4.1.tgz";
        sha512 = "pef6gxZFztEhaE9RY9HmWVmiIHqCb2OyS4HPKkpc6CIiiOa3Qmuoylxc5P2EkU3w+5eTSifI9SEZC88idAIGow==";
      };
    };
    "bitcoinjs-lib-4.0.3" = {
      name = "bitcoinjs-lib";
      packageName = "bitcoinjs-lib";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bitcoinjs-lib/-/bitcoinjs-lib-4.0.3.tgz";
        sha512 = "cb5t55MYUpwQi095J+u6eyltgIU7lbhZfC6+annstncDhfH4cyctW5jmU/tac7NonZZFYH7DktWnDxUm9AWWDQ==";
      };
    };
    "bn.js-4.11.8" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.8.tgz";
        sha512 = "ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "browser-pack-6.1.0" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-6.1.0.tgz";
        sha512 = "erYug8XoqzU3IfcU8fUgyHqyOXqIE4tUTTQ+7mqUjQlvnXkOO6OlT9c/ZoJVHYoAaqGxr09CN53G7XIsO4KtWA==";
      };
    };
    "browser-resolve-1.11.3" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.3.tgz";
        sha512 = "exDi1BYWB/6raKHmDTCicQfTkqwN5fioMFV4j8BsfMU4R2DK/QfZfK7kOVkmWCNANf0snkBzqGqAJBao9gZMdQ==";
      };
    };
    "browserify-aes-1.2.0" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.2.0.tgz";
        sha512 = "+7CHXqGuspUn/Sl5aO7Ea0xWGAtETPXNSAjHo48JfLdPWcMng33Xe4znFvQweqc/uzk5zSOI3H52CYnjCfb5hA==";
      };
    };
    "browserify-cipher-1.0.1" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.1.tgz";
        sha512 = "sPhkz0ARKbf4rRQt2hTpAHqn47X3llLkUGn+xEJzLjwY8LRs2p0v7ljvI5EyoRO/mexrNunNECisZs+gw2zz1w==";
      };
    };
    "browserify-des-1.0.2" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.2.tgz";
        sha512 = "BioO1xf3hFwz4kc6iBhI3ieDFompMhrMlnDFC4/0/vd5MokpuAc3R+LYbwTA9A5Yc9pq9UYPqffKpW2ObuwX5A==";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "browserify-sign-4.0.4" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.0.4.tgz";
        sha1 = "aa4eb68e5d7b658baa6bf6a57e630cbd7a93d298";
      };
    };
    "browserify-zlib-0.2.0" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.2.0.tgz";
        sha512 = "Z942RysHXmJrhqk88FmKBVq/v5tqmSkDz7p54G/MGyjMnCFFnC79XWNbg+Vta8W6Wb2qtSZTSxIGkJrRpCFEiA==";
      };
    };
    "bs58-4.0.1" = {
      name = "bs58";
      packageName = "bs58";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-4.0.1.tgz";
        sha1 = "be161e76c354f6f788ae4071f63f34e8c4f0a42a";
      };
    };
    "bs58check-2.1.2" = {
      name = "bs58check";
      packageName = "bs58check";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58check/-/bs58check-2.1.2.tgz";
        sha512 = "0TS1jicxdU09dwJMNZtVAfzPi6Q6QeN0pM1Fkzrjn+XYHvzMKPU3pHVpva+769iNVSfIYWf7LJ6WR+BuuMf8cA==";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "builtin-status-codes-3.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-3.0.0.tgz";
        sha1 = "85982878e21b98e1c66425e03d0174788f569ee8";
      };
    };
    "cached-path-relative-1.0.2" = {
      name = "cached-path-relative";
      packageName = "cached-path-relative";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cached-path-relative/-/cached-path-relative-1.0.2.tgz";
        sha512 = "5r2GqsoEb4qMTTN9J+WzXfjov+hjxT+j3u5K+kIVNIwAd99DLCJE9pBIMP1qVeybV6JiijL385Oz0DcYxfbOIg==";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "cheerio-0.22.0" = {
      name = "cheerio";
      packageName = "cheerio";
      version = "0.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheerio/-/cheerio-0.22.0.tgz";
        sha1 = "a9baa860a3f9b595a6b81b1a86873121ed3a269e";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "combine-source-map-0.8.0" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.8.0.tgz";
        sha1 = "a58d0df042c186fcf822a8e8015f5450d2d79a8b";
      };
    };
    "combined-stream-1.0.7" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.7.tgz";
        sha512 = "brWl9y6vOB1xYPZcpZde3N9zDByXTosAeMDo4p1wzo6UMOX4vumB+TP1RZ76sfE6Md68Q0NJSrE/gbezd4Ul+w==";
      };
    };
    "commander-2.19.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.19.0.tgz";
        sha512 = "6tvAOO+D6OENvRAh524Dh9jcfKTYDQAqvqezbCW82xj5X0pSrcpxtvRKHLG0yBY6SD7PSDrJaj+0AiOcKVd1Xg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "constants-browserify-1.0.0" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz";
        sha1 = "c20b96d8c617748aaf1c16021760cd27fcb8cb75";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "create-ecdh-4.0.3" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.3.tgz";
        sha512 = "GbEHQPMOswGpKXM9kCWVrremUcBmjteUaQ01T9rkKCPDXfUHX0IoP9LpHYo2NPFampa4e+/pFDc3jQdxrxQLaw==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "cross-fetch-2.2.3" = {
      name = "cross-fetch";
      packageName = "cross-fetch";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-fetch/-/cross-fetch-2.2.3.tgz";
        sha512 = "PrWWNH3yL2NYIb/7WF/5vFG3DCQiXDOVf8k3ijatbrtnwNuhMWLC7YF7uqf53tbTFDzHIUD8oITw4Bxt8ST3Nw==";
      };
    };
    "crypto-browserify-3.12.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.12.0.tgz";
        sha512 = "fz4spIh+znjO2VjL+IdhEpRJ3YN6sMzITSBijk6FK2UvTqruSQW+/cCZTSNsMiZNvUeq0CqurF+dAbyiGOY6Wg==";
      };
    };
    "css-select-1.2.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-1.2.0.tgz";
        sha1 = "2b3a110539c5355f1cd8d314623e870b121ec858";
      };
    };
    "css-what-2.1.3" = {
      name = "css-what";
      packageName = "css-what";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-2.1.3.tgz";
        sha512 = "a+EPoD+uZiNfh+5fxw2nO9QwFa6nJe2Or35fGY6Ipw1R3R4AGz1d1TEZrCegvw2YTmZ0jXirGYlzxxpYSHwpEg==";
      };
    };
    "dash-ast-1.0.0" = {
      name = "dash-ast";
      packageName = "dash-ast";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dash-ast/-/dash-ast-1.0.0.tgz";
        sha512 = "Vy4dx7gquTeMcQR/hDkYLGUnwVil6vk4FOOct+djUnHOUWt+zJPJAaRIXaAFkPXtJjvlY7o3rfRu0/3hpnwoUA==";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "deps-sort-2.0.0" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-2.0.0.tgz";
        sha1 = "091724902e84658260eb910748cccd1af6e21fb5";
      };
    };
    "des.js-1.0.0" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.0.tgz";
        sha1 = "c074d2e2aa6a8a9a07dbd61f9a15c2cd83ec8ecc";
      };
    };
    "detective-5.2.0" = {
      name = "detective";
      packageName = "detective";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-5.2.0.tgz";
        sha512 = "6SsIx+nUUbuK0EthKjv0zrdnajCCXVYGmbYYiYjFVpzcjwEs/JMDZ8tPRG29J/HhN56t3GJp2cGSWDRjjot8Pg==";
      };
    };
    "diffie-hellman-5.0.3" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.3.tgz";
        sha512 = "kqag/Nl+f3GwyK25fhUMYj81BUOrZ9IuJsjIcDE5icNM9FJHAVm3VcUDxdLPoQtTuUylWm6ZIknYJwwaPxsUzg==";
      };
    };
    "dom-serializer-0.1.1" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.1.tgz";
        sha512 = "l0IU0pPzLWSHBcieZbpOKgkIn3ts3vAh7ZuFyXNwJxJXk/c4Gwj9xaTJwIDVQCXawWD0qb3IzMGH5rglQaO0XA==";
      };
    };
    "domain-browser-1.2.0" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.2.0.tgz";
        sha512 = "jnjyiM6eRyZl2H+W8Q/zLMA481hzi0eszAaBUzIVnmYVDBbnLxVNnfu1HgEBvCbL+71FrxMl3E6lpKH7Ge3OXA==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domhandler-2.4.2" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.2.tgz";
        sha512 = "JiK04h0Ht5u/80fdLMCEmV4zkNh2BcoMFBmZ/91WtYZ8qVXSKjiw7fXMgFPnHcSZgOo3XdinHvmnDUeMf5R4wA==";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "ecurve-1.0.6" = {
      name = "ecurve";
      packageName = "ecurve";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecurve/-/ecurve-1.0.6.tgz";
        sha512 = "/BzEjNfiSuB7jIWKcS/z8FK9jNjmEWvUV2YZ4RLSmcDtP7Lq0m6FvDuSnJpBlDpGRpfRQeTLGLBI8H+kEv0r+w==";
      };
    };
    "elliptic-6.4.1" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.4.1.tgz";
        sha512 = "BsXLz5sqX8OHcsh7CqBMztyXARmGQ3LWPtGjJi6DiJHq5C/qvi9P3OqgswKSDftbu8+IoI/QDTAm2fFnQ9SZSQ==";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "es6-promise-4.2.6" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.6.tgz";
        sha512 = "aRVgGdnmW2OiySVPUC9e6m+plolMAJKjZnQlCwNSuK5yQ0JN61DZSO1X1Ufd1foqWRAlig0rhduTCHe7sVtK5Q==";
      };
    };
    "events-2.1.0" = {
      name = "events";
      packageName = "events";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-2.1.0.tgz";
        sha512 = "3Zmiobend8P9DjmKAty0Era4jV8oJ0yGYe2nJJAxgymF9+N8F2m0hhZiMoWtcfepExzNKZumFU3ksdQbInGWCg==";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 = "/f2Go4TognH/KvCISP7OUsHn85hT9nUkxxA9BEWxFn+Oj9o8ZNLm/40hdlgSLyuOimsrTKLUMEorQexp/aPQeA==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "fast-deep-equal-2.0.1" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-2.0.1.tgz";
        sha1 = "7b05218ddf9667bf7f370bf7fdb2cb15fdd0aa49";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.3" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.3.tgz";
        sha512 = "1lLKB2Mu3aGP1Q/2eCOx0fNbRMe7XdwktwOruhfqqd0rIJWwN4Dh+E3hrPSlDCXnSR7UtZ1N38rVXm+6+MEhJQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-assigned-identifiers-1.2.0" = {
      name = "get-assigned-identifiers";
      packageName = "get-assigned-identifiers";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz";
        sha512 = "mBBwmeGTrxEMO4pMaaf/uUEFHnYtwr8FTe8Y/mer4rcV/bye0qGm6pw1bGZFGStxC5O76c5ZAVBGnqHmOaJpdQ==";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-7.1.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.3.tgz";
        sha512 = "vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz";
        sha512 = "sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "hash-base-3.0.4" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.0.4.tgz";
        sha1 = "5fc8686847ecd73499403319a6b0a3f3f6ae4918";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 = "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "htmlparser2-3.10.1" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.10.1.tgz";
        sha512 = "IgieNijUMbkDovyoKObU1DUhm1iwNYE/fuifEoEHfd1oZKZDaONBSkal7Y01shxsM49R4XaMdGez3WnF9UfiCQ==";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "https-browserify-1.0.0" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-1.0.0.tgz";
        sha1 = "ec06c10e0a34c0f2faf199f7fd7fc78fffd03c73";
      };
    };
    "iced-error-0.0.13" = {
      name = "iced-error";
      packageName = "iced-error";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/iced-error/-/iced-error-0.0.13.tgz";
        sha512 = "yEEaG8QfyyRL0SsbNNDw3rVgTyqwHFMCuV6jDvD43f/2shmdaFXkqvFLGhDlsYNSolzYHwVLM/CrXt9GygYopA==";
      };
    };
    "iced-lock-1.1.0" = {
      name = "iced-lock";
      packageName = "iced-lock";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/iced-lock/-/iced-lock-1.1.0.tgz";
        sha1 = "6116ef1cab3acd6e6b10893bb27ba622fd3fde72";
      };
    };
    "iced-runtime-1.0.3" = {
      name = "iced-runtime";
      packageName = "iced-runtime";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iced-runtime/-/iced-runtime-1.0.3.tgz";
        sha1 = "2d4f4fb999ab7aa5430b193c77a7fce4118319ce";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inline-source-map-0.6.2" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.6.2.tgz";
        sha1 = "f9393471c18a79d1724f863fa38b586370ade2a5";
      };
    };
    "insert-module-globals-7.2.0" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.2.0.tgz";
        sha512 = "VE6NlW+WGn2/AeOMd496AHFYmE7eLKkUY6Ty31k4og5vmA3Fjuwe9v6ifH6Xx/Hz27QvdoMoviw1/pqWRB09Sw==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isarray-2.0.4" = {
      name = "isarray";
      packageName = "isarray";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-2.0.4.tgz";
        sha512 = "GMxXOiUirWg1xTKRipM0Ek07rX+ubx4nNVElTJdNLYmNO/2YrDkgJGw9CljXn+r4EWiDQg/8lsRdHyg2PJuUaA==";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "jsontokens-1.0.0" = {
      name = "jsontokens";
      packageName = "jsontokens";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsontokens/-/jsontokens-1.0.0.tgz";
        sha512 = "cC5q2qnJfwFQfN/P30Lo/m2v3x2D/JLUxli5tGP2367yRY5ZyEZSFpu+HQEBf2C8xlHL6DjQMYNFPdCFgQTmgA==";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "key-encoder-1.1.7" = {
      name = "key-encoder";
      packageName = "key-encoder";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/key-encoder/-/key-encoder-1.1.7.tgz";
        sha512 = "7qjnX+t+l1kPeozKAm3/UO216/HseXw7xxXd8WkT2i/moFIZIN46RzoaCeScBoEwGF2mUUuPRu4j8EHP0BGfpg==";
      };
    };
    "labeled-stream-splicer-2.0.1" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-2.0.1.tgz";
        sha512 = "MC94mHZRvJ3LfykJlTUipBqenZz1pacOZEMhhQ8dMGcDHs0SBE5GbsavUXV7YtP3icBW17W0Zy1I0lfASmo9Pg==";
      };
    };
    "lodash.assignin-4.2.0" = {
      name = "lodash.assignin";
      packageName = "lodash.assignin";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assignin/-/lodash.assignin-4.2.0.tgz";
        sha1 = "ba8df5fb841eb0a3e8044232b0e263a8dc6a28a2";
      };
    };
    "lodash.bind-4.2.1" = {
      name = "lodash.bind";
      packageName = "lodash.bind";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.bind/-/lodash.bind-4.2.1.tgz";
        sha1 = "7ae3017e939622ac31b7d7d7dcb1b34db1690d35";
      };
    };
    "lodash.defaults-4.2.0" = {
      name = "lodash.defaults";
      packageName = "lodash.defaults";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz";
        sha1 = "d09178716ffea4dde9e5fb7b37f6f0802274580c";
      };
    };
    "lodash.filter-4.6.0" = {
      name = "lodash.filter";
      packageName = "lodash.filter";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.filter/-/lodash.filter-4.6.0.tgz";
        sha1 = "668b1d4981603ae1cc5a6fa760143e480b4c4ace";
      };
    };
    "lodash.flatten-4.4.0" = {
      name = "lodash.flatten";
      packageName = "lodash.flatten";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.flatten/-/lodash.flatten-4.4.0.tgz";
        sha1 = "f31c22225a9632d2bbf8e4addbef240aa765a61f";
      };
    };
    "lodash.foreach-4.5.0" = {
      name = "lodash.foreach";
      packageName = "lodash.foreach";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.foreach/-/lodash.foreach-4.5.0.tgz";
        sha1 = "1a6a35eace401280c7f06dddec35165ab27e3e53";
      };
    };
    "lodash.map-4.6.0" = {
      name = "lodash.map";
      packageName = "lodash.map";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.map/-/lodash.map-4.6.0.tgz";
        sha1 = "771ec7839e3473d9c4cde28b19394c3562f4f6d3";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "lodash.merge-4.6.1" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.1.tgz";
        sha512 = "AOYza4+Hf5z1/0Hztxpm2/xiPZgi/cjMqdnKTUWTBSKchJlxXXuUSxCCl8rJlf4g6yww/j6mA8nC8Hw/EZWxKQ==";
      };
    };
    "lodash.pick-4.4.0" = {
      name = "lodash.pick";
      packageName = "lodash.pick";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.pick/-/lodash.pick-4.4.0.tgz";
        sha1 = "52f05610fff9ded422611441ed1fc123a03001b3";
      };
    };
    "lodash.reduce-4.6.0" = {
      name = "lodash.reduce";
      packageName = "lodash.reduce";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.reduce/-/lodash.reduce-4.6.0.tgz";
        sha1 = "f1ab6b839299ad48f784abbf476596f03b914d3b";
      };
    };
    "lodash.reject-4.6.0" = {
      name = "lodash.reject";
      packageName = "lodash.reject";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.reject/-/lodash.reject-4.6.0.tgz";
        sha1 = "80d6492dc1470864bbf583533b651f42a9f52415";
      };
    };
    "lodash.some-4.6.0" = {
      name = "lodash.some";
      packageName = "lodash.some";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.some/-/lodash.some-4.6.0.tgz";
        sha1 = "1bb9f314ef6b8baded13b549169b2a945eb68e4d";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "merkle-lib-2.0.10" = {
      name = "merkle-lib";
      packageName = "merkle-lib";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/merkle-lib/-/merkle-lib-2.0.10.tgz";
        sha1 = "82b8dbae75e27a7785388b73f9d7725d0f6f3326";
      };
    };
    "miller-rabin-4.0.1" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.1.tgz";
        sha512 = "115fLhvZVqWwHPbClyntxEVfVDfl9DLLTuJvq3g2O/Oxi8AiNouAHvDSzHS0viUJc+V5vm3eq91Xwqn9dp4jRA==";
      };
    };
    "mime-db-1.38.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.38.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.38.0.tgz";
        sha512 = "bqVioMFFzc2awcdJZIzR3HjZFX20QhilVS7hytkKrv7xFAn8bM1gzc/FOX2awLISvWe0PV8ptFKcon+wZ5qYkg==";
      };
    };
    "mime-types-2.1.22" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.22.tgz";
        sha512 = "aGl6TZGnhm/li6F7yx82bJiBZwgiEa4Hf6CNr8YO+r5UHr53tSTYZb102zyU50DOWWKeOv0uQLRL0/9EiKWCog==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "module-deps-6.2.0" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-6.2.0.tgz";
        sha512 = "hKPmO06so6bL/ZvqVNVqdTVO8UAYsi3tQWlCa+z9KuWhoN4KDQtb5hcqQQv58qYiDE21wIvnttZEPiDgEbpwbA==";
      };
    };
    "more-entropy-0.0.7" = {
      name = "more-entropy";
      packageName = "more-entropy";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/more-entropy/-/more-entropy-0.0.7.tgz";
        sha1 = "67bfc6f7a86f26fbc37aac83fd46d88c61d109b5";
      };
    };
    "nan-2.13.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.13.2.tgz";
        sha512 = "TghvYc72wlMGMVMluVo9WRJc0mB8KxxF/gZ4YYFy7V2ZQX9l7rgbPg7vjS9mt6U5HXODVFVI2bOduCzwOMv/lw==";
      };
    };
    "node-fetch-2.1.2" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.1.2.tgz";
        sha1 = "ab884e8e7e57e38a944753cec706f788d1768bb5";
      };
    };
    "nth-check-1.0.2" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-1.0.2.tgz";
        sha512 = "WeBOdju8SnzPN5vTUJYxYUxLeXpCaVP5i5e0LF8fg7WORF2Wd7wFX/pk0tYZk7s8T+J7VLy0Da6J1+wCT0AtHg==";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "os-browserify-0.3.0" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.3.0.tgz";
        sha1 = "854373c7f5c2315914fc9bfc6bd8238fdda1ec27";
      };
    };
    "pako-1.0.10" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.10.tgz";
        sha512 = "0DTvPVU3ed8+HNXOu5Bs+o//Mbdj9VNQMUOe9oKCwh8l0GNwpTDMKCWbRjgtD291AWnkAgkqA/LOnQS8AmS1tw==";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "parse-asn1-5.1.4" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.4.tgz";
        sha512 = "Qs5duJcuvNExRfFZ99HDD3z4mAi3r9Wl/FOjEOijlxwCZs7E7mW2vjTpgQ4J8LpTF8x5v+1Vn5UQFejmWT11aw==";
      };
    };
    "path-browserify-0.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz";
        sha512 = "BapA40NHICOS+USX9SN4tyhq+A2RrN/Ws5F0Z5aMHDp98Fl86lX8Oti8B7uN93L4Ifv4fHOEA+pQw87gmMO/lQ==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "pbkdf2-3.0.17" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.17.tgz";
        sha512 = "U/il5MsrZp7mGg3mSQfn742na2T+1/vHDCG5/iTI3X9MKUuYUZVLQhyRsg06mCgDBTd57TxzgZt7P+fYfjRLtA==";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "progress-1.1.8" = {
      name = "progress";
      packageName = "progress";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-1.1.8.tgz";
        sha1 = "e260c78f6161cdd9b0e56cc3e0a85de17c7a57be";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==";
      };
    };
    "psl-1.1.31" = {
      name = "psl";
      packageName = "psl";
      version = "1.1.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.1.31.tgz";
        sha512 = "/6pt4+C+T+wZUieKR620OpzN/LlnNKuWjy1iFLQ/UG35JqHlR/89MP1d96dUfkf6Dne3TuLQzOYEYshJ+Hx8mw==";
      };
    };
    "public-encrypt-4.0.3" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.3.tgz";
        sha512 = "zVpa8oKZSz5bTMTFClc1fQOnyyEzpl5ozpi1B5YcvBrdohMjH2rfsBtyXcuNuwjsDIXmBYlF2N5FlJYhR29t8Q==";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "pushdata-bitcoin-1.0.1" = {
      name = "pushdata-bitcoin";
      packageName = "pushdata-bitcoin";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pushdata-bitcoin/-/pushdata-bitcoin-1.0.1.tgz";
        sha1 = "15931d3cd967ade52206f523aa7331aef7d43af7";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "query-string-4.3.4" = {
      name = "query-string";
      packageName = "query-string";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-4.3.4.tgz";
        sha1 = "bbb693b9ca915c232515b228b1a02b609043dbeb";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "randomfill-1.0.4" = {
      name = "randomfill";
      packageName = "randomfill";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomfill/-/randomfill-1.0.4.tgz";
        sha512 = "87lcbR8+MhcWcUiQ+9e+Rwx8MyR2P7qnt15ynUlbm3TU/fjbgz4GsvfSUDTemtCCtVCqb4ZcEFlyPNTh9bBTLw==";
      };
    };
    "read-only-stream-2.0.0" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-2.0.0.tgz";
        sha1 = "2724fd6a8113d73764ac288d4386270c1dbf17f0";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "readable-stream-3.2.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.2.0.tgz";
        sha512 = "RV20kLjdmpZuTF1INEb9IA3L68Nmi+Ri7ppZqo78wj//Pn62fCoJyV9zalccNzDD/OuJpMG4f+pfMl8+L6QdGw==";
      };
    };
    "regenerator-runtime-0.13.2" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.2.tgz";
        sha512 = "S/TQAZJO+D3m9xeN1WTI8dLKBBiRgXBlTJvbWjCThHWZj9EvHK70Ff50/tYj2J/fvBY6JtFVwRuazHN2E7M9BA==";
      };
    };
    "request-2.88.0" = {
      name = "request";
      packageName = "request";
      version = "2.88.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.88.0.tgz";
        sha512 = "NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E+lHDAJzu7kLAkDeY08z2/A0hg==";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "resolve-1.10.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.10.0.tgz";
        sha512 = "3sUr9aq5OfSg2S9pNtPA9hL1FVEAjvfOC4leW0SNf/mpnaakz2a9femSd6LqAww2RaFctwyf1lCqnTHuF1rxDg==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "schema-inspector-1.6.8" = {
      name = "schema-inspector";
      packageName = "schema-inspector";
      version = "1.6.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/schema-inspector/-/schema-inspector-1.6.8.tgz";
        sha1 = "b9e53983cc55ff2dbd7b65e3dbe085d9d1285f2a";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shell-quote-1.6.1" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.6.1.tgz";
        sha1 = "f4781949cce402697127430ea3b3c5476f481767";
      };
    };
    "simple-concat-1.0.0" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.0.tgz";
        sha1 = "7344cbb8b6e26fb27d66b2fc86f9f6d5997521c6";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "sshpk-1.16.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.16.1.tgz";
        sha512 = "HXXqVUq7+pcKeLqqZj6mHFUMvXtOJt1uoUx09pFW6011inTMxqI8BA8PM95myrIyyKwdnzjdFjLiE6KBPVtJIg==";
      };
    };
    "stream-browserify-2.0.2" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.2.tgz";
        sha512 = "nX6hmklHs/gr2FuxYDltq8fJA1GDlxKQCz8O/IM4atRqBH8OORmBNgfvW5gG10GT/qQ9u0CzIvr2X5Pkt6ntqg==";
      };
    };
    "stream-combiner2-1.1.1" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.1.1.tgz";
        sha1 = "fb4d8a1420ea362764e21ad4780397bebcb41cbe";
      };
    };
    "stream-http-2.8.3" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-2.8.3.tgz";
        sha512 = "+TSkfINHDo4J+ZobQLWiMouQYB+UVYFttRA94FpEzzJ7ZdqcL4uUUQ7WkdkI4DSozGmgBUE/a47L+38PenXhUw==";
      };
    };
    "stream-splicer-2.0.0" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-2.0.0.tgz";
        sha1 = "1b63be438a133e4b671cc1935197600175910d83";
      };
    };
    "strict-uri-encode-1.1.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-1.1.0.tgz";
        sha1 = "279b225df1d582b1f54e65addd4352e18faa0713";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "string_decoder-1.2.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.2.0.tgz";
        sha512 = "6YqyX6ZWEYguAxgZzHGL7SsCeGx3V2TtOTqZz1xSTSWnqsbWwbptafNyvf/ACquZUXV3DANr5BDIwNYe1mN42w==";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "syntax-error-1.4.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.4.0.tgz";
        sha512 = "YPPlu67mdnHGTup2A8ff7BC2Pjq0e0Yp/IyTFN03zWO0RcK07uLcbi7C2KpGR2FvWbaB0+bfE27a+sBKebSo7w==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-2.0.5" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.5.tgz";
        sha512 = "/mrRod8xqpA+IHSLyGCQ2s8SPHiCDEeQJSep1jqLYeEUClOFG2Qsh+4FU6G9VeqpZnGW/Su8LQGc4YKni5rYSQ==";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tiny-secp256k1-1.0.1" = {
      name = "tiny-secp256k1";
      packageName = "tiny-secp256k1";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-secp256k1/-/tiny-secp256k1-1.0.1.tgz";
        sha512 = "Wz2kMPWtCI5XBftFeF3bUL8uz2+VlasniKwOkRPjvL7h1QVd9rbhrve/HWUu747kJKzVf1XHonzcdM4Ut8fvww==";
      };
    };
    "to-arraybuffer-1.0.1" = {
      name = "to-arraybuffer";
      packageName = "to-arraybuffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-arraybuffer/-/to-arraybuffer-1.0.1.tgz";
        sha1 = "7d229b1fcc637e466ca081180836a7aabff83f43";
      };
    };
    "tough-cookie-2.4.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.4.3.tgz";
        sha512 = "Q5srk/4vDM54WJsJio3XNn6K2sCG+CQ8G5Wz6bZhRZoAe/+TxjWB/GlFAnYEbkYVlON9FMk/fE3h2RLpPXo4lQ==";
      };
    };
    "triplesec-3.0.27" = {
      name = "triplesec";
      packageName = "triplesec";
      version = "3.0.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/triplesec/-/triplesec-3.0.27.tgz";
        sha512 = "FDhkxa3JYnPOerOd+8k+SBmm7cb7KkyX+xXwNFV3XV6dsQgHuRvjtbnzWfPJ2kimeR8ErjZfPd/6r7RH6epHDw==";
      };
    };
    "tty-browserify-0.0.1" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.1.tgz";
        sha512 = "C3TaO7K81YvjCgQH9Q1S3R3P3BtN3RIM8n+OvX4il1K1zgE8ZhI0op7kClgkxtutIE8hQrcrHBXvIheqKUUCxw==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "typeforce-1.18.0" = {
      name = "typeforce";
      packageName = "typeforce";
      version = "1.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typeforce/-/typeforce-1.18.0.tgz";
        sha512 = "7uc1O8h1M1g0rArakJdf0uLRSSgFcYexrVoKo+bzJd32gd4gDy2L/Z+8/FjPnU9ydY3pEnVPtr9FyscYY60K1g==";
      };
    };
    "uglify-js-3.5.2" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.5.2.tgz";
        sha512 = "imog1WIsi9Yb56yRt5TfYVxGmnWs3WSGU73ieSOlMVFwhJCA9W8fqFFMMj4kgDqiS/80LGdsYnWL7O9UcjEBlg==";
      };
    };
    "umd-3.0.3" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.3.tgz";
        sha512 = "4IcGSufhFshvLNcMCV80UnQVlZ5pMOC8mvNPForqwA4+lzYQuetTESLDQkeLmihq8bRcnpbQa48Wb8Lh16/xow==";
      };
    };
    "undeclared-identifiers-1.1.3" = {
      name = "undeclared-identifiers";
      packageName = "undeclared-identifiers";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz";
        sha512 = "pJOW4nxjlmfwKApE4zvxLScM/njmwj/DiUBv7EabwE4O8kRUy+HIwxQtZLBPll/jx1LJyBcqNfB3/cpv9EZwOw==";
      };
    };
    "unorm-1.5.0" = {
      name = "unorm";
      packageName = "unorm";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unorm/-/unorm-1.5.0.tgz";
        sha512 = "sMfSWoiRaXXeDZSXC+YRZ23H4xchQpwxjpw1tmfR+kgbBCaOgln4NI0LXejJIhnBuKINrB3WRn+ZI8IWssirVw==";
      };
    };
    "uri-js-4.2.2" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.2.2.tgz";
        sha512 = "KY9Frmirql91X2Qgjry0Wd4Y+YTdrdZheS8TFwvkbLWf/G5KNJDCh6pKL5OZctEW4+0Baa5idK2ZQuELRwPznQ==";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "util-0.10.4" = {
      name = "util";
      packageName = "util";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.4.tgz";
        sha512 = "0Pm9hTQ3se5ll1XihRic3FDIku70C+iHUdT/W926rSgHV5QgXsYbKZN8MSC3tJtSkhuROzvsQjAaFENRXr+19A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "validator-10.11.0" = {
      name = "validator";
      packageName = "validator";
      version = "10.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-10.11.0.tgz";
        sha512 = "X/p3UZerAIsbBfN/IwahhYaBbY68EN/UQBWHtsbXGT5bfrH/p4NQzUCG1kF/rtKaNpnJ7jAu6NGTdSNtyNIXMw==";
      };
    };
    "validator-7.2.0" = {
      name = "validator";
      packageName = "validator";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-7.2.0.tgz";
        sha512 = "c8NGTUYeBEcUIGeMppmNVKHE7wwfm3mYbNZxV+c5mlv9fDHI7Ad3p07qfNrn/CvpdkK2k61fOLRO2sTEhgQXmg==";
      };
    };
    "varuint-bitcoin-1.1.0" = {
      name = "varuint-bitcoin";
      packageName = "varuint-bitcoin";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varuint-bitcoin/-/varuint-bitcoin-1.1.0.tgz";
        sha512 = "jCEPG+COU/1Rp84neKTyDJQr478/hAfVp5xxYn09QEH0yBjbmPeMfuuQIrp+BUD83hybtYZKhr5elV3bvdV1bA==";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "vm-browserify-1.1.0" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-1.1.0.tgz";
        sha512 = "iq+S7vZJE60yejDYM0ek6zg308+UZsdtPExWP9VZoCFCz1zkJoXFnAX7aZfd/ZwrkidzdUZL0C/ryW+JwAiIGw==";
      };
    };
    "whatwg-fetch-2.0.4" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.4.tgz";
        sha512 = "dcQ1GWpOD/eEQ97k66aiEVpNnapVj90/+R+SXTPYGHpYBBypfKJEQjLrvMZ7YXbKm21gXd4NcuxUTjiv1YtLng==";
      };
    };
    "wif-2.0.6" = {
      name = "wif";
      packageName = "wif";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/wif/-/wif-2.0.6.tgz";
        sha1 = "08d3f52056c66679299726fade0d432ae74b4704";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "zone-file-1.0.0" = {
      name = "zone-file";
      packageName = "zone-file";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/zone-file/-/zone-file-1.0.0.tgz";
        sha512 = "dJynTf/5XCobE6diQBpNWQQRBzXE8d1QhHKemzrkffrZ36F9uKlbBVyIXXbG2CJoaTGZGh8zt2AHX/mG4txtqA==";
      };
    };
  };
in
{
  browserify = nodeEnv.buildNodePackage {
    name = "browserify";
    packageName = "browserify";
    version = "16.2.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/browserify/-/browserify-16.2.3.tgz";
      sha512 = "zQt/Gd1+W+IY+h/xX2NYMW4orQWhqSwyV+xsblycTtpOuB27h1fZhhNQuipJ4t79ohw4P4mMem0jp/ZkISQtjQ==";
    };
    dependencies = [
      sources."JSONStream-1.3.5"
      sources."acorn-6.1.1"
      sources."acorn-dynamic-import-4.0.0"
      sources."acorn-node-1.6.2"
      sources."acorn-walk-6.1.1"
      sources."array-filter-0.0.1"
      sources."array-map-0.0.0"
      sources."array-reduce-0.0.0"
      sources."asn1.js-4.10.1"
      (sources."assert-1.4.1" // {
        dependencies = [
          sources."inherits-2.0.1"
          sources."util-0.10.3"
        ];
      })
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.0"
      sources."bn.js-4.11.8"
      sources."brace-expansion-1.1.11"
      sources."brorand-1.1.0"
      sources."browser-pack-6.1.0"
      (sources."browser-resolve-1.11.3" // {
        dependencies = [
          sources."resolve-1.1.7"
        ];
      })
      sources."browserify-aes-1.2.0"
      sources."browserify-cipher-1.0.1"
      sources."browserify-des-1.0.2"
      sources."browserify-rsa-4.0.1"
      sources."browserify-sign-4.0.4"
      sources."browserify-zlib-0.2.0"
      sources."buffer-5.2.1"
      sources."buffer-from-1.1.1"
      sources."buffer-xor-1.0.3"
      sources."builtin-status-codes-3.0.0"
      sources."cached-path-relative-1.0.2"
      sources."cipher-base-1.0.4"
      sources."combine-source-map-0.8.0"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.6.2"
      sources."console-browserify-1.1.0"
      sources."constants-browserify-1.0.0"
      sources."convert-source-map-1.1.3"
      sources."core-util-is-1.0.2"
      sources."create-ecdh-4.0.3"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crypto-browserify-3.12.0"
      sources."dash-ast-1.0.0"
      sources."date-now-0.1.4"
      sources."defined-1.0.0"
      sources."deps-sort-2.0.0"
      sources."des.js-1.0.0"
      (sources."detective-5.2.0" // {
        dependencies = [
          sources."minimist-1.2.0"
        ];
      })
      sources."diffie-hellman-5.0.3"
      sources."domain-browser-1.2.0"
      sources."duplexer2-0.1.4"
      sources."elliptic-6.4.1"
      sources."events-2.1.0"
      sources."evp_bytestokey-1.0.3"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."get-assigned-identifiers-1.2.0"
      sources."glob-7.1.3"
      sources."has-1.0.3"
      sources."hash-base-3.0.4"
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."htmlescape-1.1.1"
      sources."https-browserify-1.0.0"
      sources."ieee754-1.1.13"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."inline-source-map-0.6.2"
      sources."insert-module-globals-7.2.0"
      sources."is-buffer-1.1.6"
      sources."isarray-2.0.4"
      sources."json-stable-stringify-0.0.1"
      sources."jsonify-0.0.0"
      sources."jsonparse-1.3.1"
      sources."labeled-stream-splicer-2.0.1"
      sources."lodash.memoize-3.0.4"
      sources."md5.js-1.3.5"
      sources."miller-rabin-4.0.1"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."module-deps-6.2.0"
      sources."once-1.4.0"
      sources."os-browserify-0.3.0"
      sources."pako-1.0.10"
      sources."parents-1.0.1"
      sources."parse-asn1-5.1.4"
      sources."path-browserify-0.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."path-platform-0.11.15"
      sources."pbkdf2-3.0.17"
      sources."process-0.11.10"
      sources."process-nextick-args-2.0.0"
      sources."public-encrypt-4.0.3"
      sources."punycode-1.4.1"
      sources."querystring-0.2.0"
      sources."querystring-es3-0.2.1"
      sources."randombytes-2.1.0"
      sources."randomfill-1.0.4"
      sources."read-only-stream-2.0.0"
      (sources."readable-stream-2.3.6" // {
        dependencies = [
          sources."isarray-1.0.0"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."resolve-1.10.0"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.1.2"
      sources."sha.js-2.4.11"
      sources."shasum-1.0.2"
      sources."shell-quote-1.6.1"
      sources."simple-concat-1.0.0"
      sources."source-map-0.5.7"
      sources."stream-browserify-2.0.2"
      sources."stream-combiner2-1.1.1"
      sources."stream-http-2.8.3"
      sources."stream-splicer-2.0.0"
      sources."string_decoder-1.2.0"
      (sources."subarg-1.0.0" // {
        dependencies = [
          sources."minimist-1.2.0"
        ];
      })
      sources."syntax-error-1.4.0"
      sources."through-2.3.8"
      sources."through2-2.0.5"
      sources."timers-browserify-1.4.2"
      sources."to-arraybuffer-1.0.1"
      sources."tty-browserify-0.0.1"
      sources."typedarray-0.0.6"
      sources."umd-3.0.3"
      sources."undeclared-identifiers-1.1.3"
      (sources."url-0.11.0" // {
        dependencies = [
          sources."punycode-1.3.2"
        ];
      })
      sources."util-0.10.4"
      sources."util-deprecate-1.0.2"
      sources."vm-browserify-1.1.0"
      sources."wrappy-1.0.2"
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "browser-side require() the node way";
      homepage = "https://github.com/browserify/browserify#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  blockstack = nodeEnv.buildNodePackage {
    name = "blockstack";
    packageName = "blockstack";
    version = "19.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/blockstack/-/blockstack-19.0.1.tgz";
      sha512 = "UdBKyg/Y17M+i+yHTHjayyrThKrQ7z4jUsYTHfHQy25Yhg1a4QWzgzfFGtoTX8Id6Zat90iINupSKaPmXiM15Q==";
    };
    dependencies = [
      sources."@babel/runtime-7.4.2"
      sources."ajv-4.11.8"
      sources."asap-2.0.6"
      sources."asn1-0.2.4"
      sources."asn1.js-5.0.1"
      sources."assert-plus-1.0.0"
      sources."async-1.5.2"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.8.0"
      sources."base-x-3.0.5"
      sources."base64url-3.0.1"
      sources."bcrypt-pbkdf-1.0.2"
      sources."bech32-1.1.3"
      sources."bigi-1.4.2"
      sources."bindings-1.5.0"
      sources."bip32-1.0.2"
      sources."bip39-2.5.0"
      sources."bip66-1.1.5"
      sources."bitcoin-ops-1.4.1"
      sources."bitcoinjs-lib-4.0.3"
      sources."bn.js-4.11.8"
      sources."boolbase-1.0.0"
      sources."brorand-1.1.0"
      sources."bs58-4.0.1"
      sources."bs58check-2.1.2"
      sources."caseless-0.12.0"
      sources."cheerio-0.22.0"
      sources."cipher-base-1.0.4"
      sources."co-4.6.0"
      sources."combined-stream-1.0.7"
      sources."commander-2.19.0"
      sources."core-util-is-1.0.2"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."cross-fetch-2.2.3"
      sources."css-select-1.2.0"
      sources."css-what-2.1.3"
      sources."dashdash-1.14.1"
      sources."delayed-stream-1.0.0"
      sources."dom-serializer-0.1.1"
      sources."domelementtype-1.3.1"
      sources."domhandler-2.4.2"
      sources."domutils-1.5.1"
      sources."ecc-jsbn-0.1.2"
      sources."ecurve-1.0.6"
      sources."elliptic-6.4.1"
      sources."entities-1.1.2"
      sources."es6-promise-4.2.6"
      sources."extend-3.0.2"
      sources."extsprintf-1.3.0"
      sources."fast-deep-equal-2.0.1"
      sources."fast-json-stable-stringify-2.0.0"
      sources."file-uri-to-path-1.0.0"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.3"
      sources."getpass-0.1.7"
      sources."har-schema-2.0.0"
      (sources."har-validator-5.1.3" // {
        dependencies = [
          sources."ajv-6.10.0"
        ];
      })
      sources."hash-base-3.0.4"
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."htmlparser2-3.10.1"
      sources."http-signature-1.2.0"
      sources."iced-error-0.0.13"
      sources."iced-lock-1.1.0"
      sources."iced-runtime-1.0.3"
      sources."inherits-2.0.3"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.4.1"
      sources."json-stable-stringify-1.0.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsonify-0.0.0"
      (sources."jsontokens-1.0.0" // {
        dependencies = [
          sources."validator-10.11.0"
        ];
      })
      sources."jsprim-1.4.1"
      sources."key-encoder-1.1.7"
      sources."lodash.assignin-4.2.0"
      sources."lodash.bind-4.2.1"
      sources."lodash.defaults-4.2.0"
      sources."lodash.filter-4.6.0"
      sources."lodash.flatten-4.4.0"
      sources."lodash.foreach-4.5.0"
      sources."lodash.map-4.6.0"
      sources."lodash.merge-4.6.1"
      sources."lodash.pick-4.4.0"
      sources."lodash.reduce-4.6.0"
      sources."lodash.reject-4.6.0"
      sources."lodash.some-4.6.0"
      sources."md5.js-1.3.5"
      sources."merkle-lib-2.0.10"
      sources."mime-db-1.38.0"
      sources."mime-types-2.1.22"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."more-entropy-0.0.7"
      sources."nan-2.13.2"
      sources."node-fetch-2.1.2"
      sources."nth-check-1.0.2"
      sources."oauth-sign-0.9.0"
      sources."object-assign-4.1.1"
      sources."pbkdf2-3.0.17"
      sources."performance-now-2.1.0"
      sources."progress-1.1.8"
      sources."promise-7.3.1"
      sources."psl-1.1.31"
      sources."punycode-2.1.1"
      sources."pushdata-bitcoin-1.0.1"
      sources."qs-6.5.2"
      sources."query-string-4.3.4"
      sources."randombytes-2.1.0"
      sources."readable-stream-3.2.0"
      sources."regenerator-runtime-0.13.2"
      sources."request-2.88.0"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."schema-inspector-1.6.8"
      sources."sha.js-2.4.11"
      sources."source-map-0.6.1"
      sources."sprintf-js-1.1.2"
      sources."sshpk-1.16.1"
      sources."strict-uri-encode-1.1.0"
      sources."string_decoder-1.2.0"
      sources."tiny-secp256k1-1.0.1"
      (sources."tough-cookie-2.4.3" // {
        dependencies = [
          sources."punycode-1.4.1"
        ];
      })
      sources."triplesec-3.0.27"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."typeforce-1.18.0"
      sources."uglify-js-3.5.2"
      sources."unorm-1.5.0"
      sources."uri-js-4.2.2"
      sources."util-deprecate-1.0.2"
      sources."uuid-3.3.2"
      sources."validator-7.2.0"
      sources."varuint-bitcoin-1.1.0"
      sources."verror-1.10.0"
      sources."whatwg-fetch-2.0.4"
      sources."wif-2.0.6"
      sources."zone-file-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The Blockstack Javascript library for authentication, identity, and storage.";
      homepage = https://blockstack.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}